AWSTemplateFormatVersion: '2010-09-09'

Description: S3 Bucket and policy for DataOffice Minerva

Parameters:

  BucketName:
    Type: String
    Description: The name of the S3 Bucket to create
  AccessControl: 
    Type: String
    Default: "PublicRead"

Resources:
    MinervaBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref BucketName
        AccessControl: !Ref AccessControl
        Tags:
          - Key: info:app
            Value: "Minerva"
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref MinervaBucket
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: !Join ['', ['arn:aws:s3:::', !Ref 'MinervaBucket', /minerva/*]]
              Principal:
                AWS:
                  # List of AWS Accounts for cross-account subscriptions
                  - !Sub 'arn:aws:iam::060126977165:user-minerva'